# Generated by Django 2.1.7 on 2019-04-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.FileField(blank=True, upload_to='courses/image'),
        ),
    ]
