# Generated by Django 2.1.7 on 2019-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190413_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.FileField(upload_to='courses/image'),
        ),
    ]
