# Generated by Django 2.1.7 on 2019-04-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='introductory_video',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome da Aula'),
        ),
    ]
